<?php
/**
 * Micro Theme Custom Hooks
 *
 * This file defines custom action and filter hooks for the Oenology Theme.
 *
 * The first section defines action hooks, which are used to append to Oenology Theme
 * template locations, and which are generally defined using terms descriptive of their
 * location, and suffixed with "_before" or "_after".
 *
 * The second section defines filter hooks, which are used to add to or to replace content
 * generated by Oenology Theme, and which are generally defined using terms descriptive of
 * their content function/location.
 *
 * In almost all cases, a given filter hook will have accompanying "_before" and "_after"
 * action hooks. This arrangement facilitates appending content before and/or after
 * Theme-generated content, or to change and/or replace entirely all Theme-generated content.
 *
 * For more information on hooks, actions, and filters, 
 * see {@link http://codex.wordpress.org/Plugin_API Plugin API}.
 * 
 * @package 	Micro
 * @copyright	Copyright (c) 2011, UpThemes
 * @license		http://www.gnu.org/licenses/old-licenses/gpl-2.0.html GNU General Public License, v2 (or newer)
 *
 * @since 		Micro 1.0
 */

/**
 * Action hook before site header
 * 
 * This action hook fires before the site header. It
 * can be used to add content before site header text 
 * is output.
 * 
 * Template file: header.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_before_header
 * 
 * @since	Micro 1.0
 * 
 */
function micro_before_header(){
	do_action('micro_before_header');
}

/**
 * Action hook for site header
 * 
 * This action hook fires for the site header. It
 * can be used to add content to the site header output.
 * 
 * Template file: header.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_header
 * 
 * @since	Micro 1.0
 * 
 */
function micro_header(){
	do_action('micro_header');
}

/**
 * Action hook after site header
 * 
 * This action hook fires after the site header. It
 * can be used to add content after site header text 
 * is output.
 * 
 * Template file: header.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_after_header
 * 
 * @since	Micro 1.0
 * 
 */
function micro_after_header(){
	do_action('micro_after_header');
}

/**
 * Action hook before site content
 * 
 * This action hook fires before the site content. It
 * can be used to add content before the site content 
 * is output.
 * 
 * Template file: header.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_before_content
 * 
 * @since	Micro 1.0
 * 
 */
function micro_before_content(){
	do_action('micro_before_content');
}

/**
 * Action hook after site content
 * 
 * This action hook fires after the site content. It
 * can be used to add content after the site content 
 * is output.
 * 
 * Template file: footer.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_after_content
 * 
 * @since	Micro 1.0
 * 
 */
function micro_after_content(){
	do_action('micro_after_content');
}

/**
 * Action hook before main sidebar
 * 
 * This action hook fires before the main sidebar. It
 * can be used to add content before the main sidebar 
 * is output.
 * 
 * Template file: sidebar.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_before_sidebar
 * 
 * @since	Micro 1.0
 * 
 */
function micro_before_sidebar(){
	do_action('micro_before_sidebar');
}

/**
 * Action hook after main sidebar
 * 
 * This action hook fires after the main sidebar. It
 * can be used to add content after the main sidebar 
 * is output.
 * 
 * Template file: sidebar.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_after_sidebar
 * 
 * @since	Micro 1.0
 * 
 */
function micro_after_sidebar(){
	do_action('micro_after_sidebar');
}

/**
 * Action hook before posts loop
 * 
 * This action hook fires before the posts loop. It
 * can be used to add content before posts loop content
 * is output.
 * 
 * Template file: header.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_before_posts
 * 
 * @since	Micro 1.0
 * 
 */
function micro_before_posts(){
	do_action('micro_before_posts');
}

/**
 * Action hook after posts loop
 * 
 * This action hook fires after the posts loop. It
 * can be used to add content after posts loop content
 * is output.
 * 
 * Template file: footer.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_after_posts
 * 
 * @since	Micro 1.0
 * 
 */
function micro_after_posts(){
	do_action('micro_after_posts');
}

/**
 * Action hook before post title
 * 
 * This action hook fires before the post title. It
 * can be used to add content before post title text 
 * is output.
 * 
 * Fired inside of micro_post_title() function, which
 * is defined in /inc/extensions/content-extensions.php,
 * and is hooked into the micro_post_title hook, defined
 * in this file.
 * 
 * Template file: content.php, content-page.php, content-single.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_before_header
 * 
 * @since	Micro 1.0
 * 
 */
function micro_before_title(){
	do_action('micro_before_title');
}

/**
 * Action hook after post title
 * 
 * This action hook fires after the post title. It
 * can be used to add content after post title text 
 * is output.
 * 
 * Fired inside of micro_post_title() function, which
 * is defined in /inc/extensions/content-extensions.php,
 * and is hooked into the micro_post_title hook, defined
 * in this file.
 * 
 * Template file: content.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_after_header
 * 
 * @since	Micro 1.0
 * 
 */
function micro_after_title(){
	do_action('micro_after_title');
}

/**
 * Action hook for the post header
 * 
 * This action hook fires for the post header. It
 * can be used to add content to the post header content.
 * 
 * Template file: content.php, content-page.php, content-single.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_post_header
 * 
 * @since	Micro 1.0
 * 
 */
function micro_post_header(){
	do_action('micro_post_header');
}

/**
 * Action hook for the post footer
 * 
 * This action hook fires for the post footer. It
 * can be used to add content to the post footer content.
 * 
 * Template file: content.php, content-single.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_post_footer
 * 
 * @since	Micro 1.0
 * 
 */
function micro_post_footer(){
	do_action('micro_post_footer');
}

/**
 * Action hook for post comments
 * 
 * This action hook fires for post comments. It
 * can be used to add content to the post comments content.
 * 
 * Template file: content.php, content-single.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_comments
 * 
 * @since	Micro 1.0
 * 
 */
function micro_comments(){
	do_action('micro_comments');
}

/**
 * Action hook before post comments
 * 
 * This action hook fires before post comments. It
 * can be used to add content before post comments content is output.
 * 
 * Template file: comments.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_comments
 * 
 * @since Micro 1.0
 */
function micro_before_comments() {
	do_action( 'micro_before_comments' );
}

/**
 * Action hook after post comments
 * 
 * This action hook fires after post comments. It
 * can be used to add content after post comments content is output.
 * 
 * Template file: comments.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_comments
 * 
 * @since Micro 1.0
 */
function micro_after_comments() {
	do_action( 'micro_after_comments' );
}

/**
 * Action hook for post metadata
 * 
 * This action hook fires for post metadata. It
 * can be used to add content to post metadata content.
 * 
 * Fired inside of micro_showmeta() function, which
 * is defined in /inc/extensions/content-extensions.php,
 * and is hooked into the micro_post_footer hook, defined
 * in this file.
 * 
 * Template file: content.php, content-single.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_postmeta
 * 
 * @since	Micro 1.0
 * 
 */
function micro_postmeta(){
	do_action('micro_postmeta');
}

/**
 * Action hook before site footer
 * 
 * This action hook fires before the site footer. It
 * can be used to add content before site footer text 
 * is output.
 * 
 * Template file: footer.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_before_footer
 * 
 * @since	Micro 1.0
 * 
 */
function micro_before_footer(){
	do_action('micro_before_footer');
}

/**
 * Action hook for site footer
 * 
 * This action hook fires for the site footer. It
 * can be used to add content to the site footer content.
 * 
 * Template file: footer.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_footer
 * 
 * @since	Micro 1.0
 * 
 */
function micro_footer(){
	do_action('micro_footer');
}

/**
 * Action hook after site footer
 * 
 * This action hook fires after the site footer. It
 * can be used to add content after site footer text 
 * is output.
 * 
 * Template file: footer.php
 * 
 * @link 		http://codex.wordpress.org/Function_Reference/do_action 	do_action()
 * 
 * @param	none
 * @return	mixed	Any output from add_action() callbacks hooked into micro_after_footer
 * 
 * @since	Micro 1.0
 * 
 */
function micro_after_footer(){
	do_action('micro_after_footer');
}